;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        help
        scroll-other-window-down
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        cua-delete-region
        handle-switch-frame
        nxml-electric-slash
        reindent-then-newline-and-indent
        smex
        ))
