;;(live-add-pack-lib "yasnippet")
(package-install 'yasnippet)
(require 'yasnippet)
(setq live-yasnippet-dir (concat live-etc-dir "snippets"))
(setq yas-snippet-dirs `(,live-yasnippet-dir))
(yas-global-mode 1)
